# Basic
title: 马老三
subtitle: 个人博客
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: 生活不止眼前的苟且，还有诗和远方
creator: <a href="http://onev.cat">@onevcat</a>

url: "https://matieli.github.io/"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

#2016-08-12 更换成 kramdown
#markdown: redcarpet
#redcarpet:
 # extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

#2016-08-12 更换成 kramdown
kramdown:
  input: GFM
  #toc_levels: 2..3
  extensions:
    - autolink
    - footnotes
    - smart
  enable_coderay: true
  syntax_highlighter: rouge
  coderay:
    coderay_line_numbers:  nil
 
# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: Dba Log, description: DbaLog, url: 'http://www.dbalog.net/'}
    - {title: Share Hub, description: Share Hub, url: 'http://blog.xiaohansong.com/'}
    - {title: 关于, description: 关于, url: '/about'}
    
# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    #disqus: leopard
    duoshuo: matieli
    
# Social
social:
    #weibo: onevcat
    github: matieli
    #twitter: onevcat
    #gplus: 107108267983477358170
    mail: matielizhangyan@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
